# perfil padrao é h2, troca pra mysql quando for rodar de verdade
spring.profiles.active=h2

# actuator - precisei habilitar o health pra funcionar com o teste selenium
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
